# Generated by Django 3.2.7 on 2021-10-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nome_titulo',
        ),
    ]
